### ISSUE TITLE
Using the approach on new traffic counter datasets

### ISSUE THREAD

**Issue by Robinlovelace** [wengwenchao123/DDGCRN#10]
Hi @wengwenchao123, I'm wondering about using the approach to estimate traffic on roads based on this input: https://roadtraffic.dft.gov.uk/

I've had a look at the code but not sure where to start, do you have an example of the structure that the input dataset needs to be in before running predictive model? 

Thanks for sharing.

**Comment by wengwenchao123** [comment]
Thank you for your attention to this work. The structure of the input data of DDGCRN is [B, TN, D], where B is the batch size, T is the time length of the input data, N is the number of nodes, and D is the number of features.The other three dimensions are easy to understand, but D needs to pay attention. It is divided into three features, one is traffic flow, and the other two are time information indexes (day level and week level). You can run debug tests on the data sets we provide to observe what the specific data looks like.

Hope it helps you.
