### ISSUE TITLE
Confusion about the code according to "Model Training" part

### ISSUE THREAD

**Issue by MapleHermione** [wengwenchao123/DDGCRN#11]
I'm confused about the code under the section "Model Training".  I wonder if the right code should be "python run.py --dataset {DATASET_NAME} --mode {MODE_NAME}" instead  of "python run.py --datasets {DATASET_NAME} --mode {MODE_NAME}". When using the code you provided, an error of "run.py: error: unrecognized arguments: --datasets PEMSD4" would occur.
I look forward to your reply.

**Comment by wengwenchao123** [comment]
Thank you for your attention to this work. Your perspective is correct, and I have already revised the corresponding parameter description. I appreciate it greatly.

**Comment by MapleHermione** [comment]
Thank you for your reply.
