### ISSUE TITLE
t-SNE可视化

### ISSUE THREAD

**Issue by NoHesitation1** [wengwenchao123/DDGCRN#12]
你好，请问关于论文中使用t-SNE进行时空嵌入可视化代码是如何实现的，方便的话 能求一份代码吗

**Comment by wengwenchao123** [comment]
额，你是想看可视化部分的代码，还是想看这个我这个图想呈现出来是怎么确定节点的

**Comment by NoHesitation1** [comment]
是的 我想看代码层面如何实现的。感谢！如果方便可以发到邮箱Longxi2745@163.com

**Comment by wengwenchao123** [comment]
发你了，这个是我当时画图用的

**Comment by NoHesitation1** [comment]
十分感谢！！！

**Comment by wengwenchao123** [comment]
不客气

**Comment by Dx3281101** [comment]
你好，可视化部分的代码方便发我一份吗，感谢！如果方便可以发到邮箱d723445197@gmail.com

**Comment by wengwenchao123** [comment]
> 你好，可视化部分的代码方便发我一份吗，感谢！如果方便可以发到邮箱[d723445197@gmail.com](mailto:d723445197@gmail.com)

你好，我发你邮箱了，看看有没有收到

**Comment by Dx3281101** [comment]
> > 你好，可视化部分的代码方便发我一份吗，感谢！如果方便可以发到邮箱[d723445197@gmail.com](mailto:d723445197@gmail.com)
> 
> 你好，我发你邮箱了，看看有没有收到

收到了，非常感谢！

**Comment by jobcccc** [comment]
作者您好，方便也发我一份吗？我的邮箱是1050892279@qq.com，非常感谢！

**Comment by wengwenchao123** [comment]
> 1050892279@qq.com

你好，我发到邮箱里了，看看有没有收到

**Comment by jobcccc** [comment]
> > [1050892279@qq.com](mailto:1050892279@qq.com)
> 
> 你好，我发到邮箱里了，看看有没有收到

收到啦！非常感谢！
