### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Vitalitypi** [wengwenchao123/DDGCRN#2]
您好，请问本项目使用的数据集中“PEMS04.csv”文件中的“from,to,cost”分别代表什么意思呢？

**Comment by wengwenchao123** [comment]
你好，“PEMS04.csv”文件是PEMS04数据集的邻接矩阵文件，是利用现实中道路节点之间的距离来得到的，里面的from代表出发的节点，to代表到达的节点，cost代表中间的道路距离

**Comment by Vitalitypi** [comment]
收到，感谢感谢
