### ISSUE TITLE
请问，在数据集PEMS03上得到的MAPE值非常大，是怎么回事呢？

### ISSUE THREAD

**Issue by RongzhangCheng** [wengwenchao123/DDGCRN#5]

**Comment by wengwenchao123** [comment]
你好，关于这个问题你可以参考一下回复，修正好的代码我会等雅思考出拿到博士机会后改好放上来

抱歉，刚才链接放错了，现在这是是正确的的[https://github.com/wengwenchao123/DDGCRN/issues/3](https://github.com/wengwenchao123/DDGCRN/issues/3)
