### ISSUE TITLE
Segmented learning training strategy

### ISSUE THREAD

**Issue by Vitalitypi** [wengwenchao123/DDGCRN#7]
您好，请问您使用分段学习了吗，我看到源码的第一层训练并没有执行？望解答

**Comment by wengwenchao123** [comment]
你好，我使用了分段学习，我设置的数量在20个epoch，因为分段学习不会影响最终效果，所以在最后整理代码阶段，我去掉了分段学习来生成代码中提供的模型参数，你可以讲epoch设置成20来执行分段学习。

**Comment by Vitalitypi** [comment]
收到，非常感谢！
