### ISSUE TITLE
想请教一个问题

### ISSUE THREAD

**Issue by OvOYu** [wengwenchao123/DDGCRN#8]
![image](https://github.com/wengwenchao123/DDGCRN/assets/107761563/1233b514-4c2a-49c9-ad3f-54c7943cf9e3)
AGCRN里反归一化的我看是label，这里反归一化是output 我不太明白区别在哪 或者是我代码看的不够仔细 希望得到您的帮助 您说后面两年发的顶会指的是哪一篇呢

**Comment by wengwenchao123** [comment]
你好，是这样子的，归一化和反归一化原本的目的是为了加快了梯度下降求最优解的速度以及可能提高精度。
AGCRN中反归一化label会导致模型是根据真实值进行拟合训练，这种情况下，真实值如果很大的话，那会导致模型在训练初期loss很难下降，你用AGCRN进行训练的时候能看到她的loss一开始会很大，要经过很久才能降下来。另外如果直接拟合真实值进行训练，会增加模型训练的难度，因为如果真实值很大的话，模型会很难拟合，导致没到最优解就训练不下去了。在归一化情况下进行训练，模型参数会好拟合很多，你可以在AGCRN中将代码修改成 
`label = self.scaler.inverse_transform(label)
`
`output = self.scaler.inverse_transform(output)`
来进行训练看看两者的差异性，你会发现这样子训练更快而且最终的效果很好很多。至于你问的后面两年的顶会，我指的是STG-NCDE，Z-GCNETs等论文，这些论文中的AGCRN中效果应该是按AGCRN的代码跑出来的，但是我将output也进行反归一化后，我发现AGCRN的效果能和上面的顶会效果持平或者更好，所以AGCRN的效果其实能够更好而不是论文里写出来的值那样子。
至于我这边反归一化的是output，是因为我在数据处理阶段将历史数据data进行了归一化，真实值label并没有进行归一化，直接保持原始大小,这样子将output进行反归一化后就是两者都是真实值大小的了。
至于在我原本的写法中，是在数据处理阶段将两者都进行归一化，然后在训练阶段和测试阶段将两者进行反归一化来训练和测试，也就是我上面写的代码，这样子其实也能达到同样的效果，但是在PEMS03数据集上，这样子做MAPE的值会出现异常，你会发现MAPE大的离谱。你可以在commit上看我做了什么修改，还原原本的代码训练看看进行对比，你就能看到两者在PEMS03上输出结果的差异性。
这个问题的原因是label在反归一化的时候，会因为误差导致原本真实值为0的数据变成0.000几的值，这样子会导致在计算MAPE的时候原本为0的label也被拿进来计算(原本根据MAPE的公式，label=0的数据室被排除在计算之外的)，然后优于MAPE的对极端值的敏感性导致MAPE异常，你可以在看这个大佬的解释理解一下，我进行优化的三个问题都在这里。https://zhuanlan.zhihu.com/p/618579344

希望能够帮到你

**Comment by wengwenchao123** [comment]
> ![image](https://private-user-images.githubusercontent.com/107761563/302112956-1233b514-4c2a-49c9-ad3f-54c7943cf9e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDgzNzYsIm5iZiI6MTcwNzEwODA3NiwicGF0aCI6Ii8xMDc3NjE1NjMvMzAyMTEyOTU2LTEyMzNiNTE0LTRjMmEtNDljOS1hZDNmLTU0Yzc5NDNjZjllMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNDQxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGUwNzU4NmQ1NmNiODhhMTBhZGU1N2QyZTI2ZWM2NjEwYmU4MzdhY2IxYWMyZTVhOTI4OWI3NzllMjJkMWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VV8lHcTWQsl5hZ7EGGMFkiQPzAv58fpbQNpjLet3fqU) AGCRN里反归一化的我看是label，这里反归一化是output 我不太明白区别在哪 或者是我代码看的不够仔细 希望得到您的帮助 您说后面两年发的顶会指的是哪一篇呢

你好，请问我上面的回答你能理解吗

**Comment by OvOYu** [comment]
感谢您的回复，我刚才正在认真理解，对我的帮助很大

**Comment by wengwenchao123** [comment]
不客气，能帮到你就好

**Comment by OvOYu** [comment]
![image](https://github.com/wengwenchao123/DDGCRN/assets/107761563/57ceac0b-c8da-49dc-a5d7-e99d5202e665)
![image](https://github.com/wengwenchao123/DDGCRN/assets/107761563/00e98ce9-cb2e-4381-ae63-6907ddcd8413)
xiabngqi想请问您一个AGCRN中的问题 teacher_forcing_ratio我不太明白在代码中的作用 默认设置为false即进入else设置为1，在第二张图模型中虽然传入了teacher_forcing_ratio但没有调用，对此我不太理解这个的作用。特别感激您在上面详细的回复！

**Comment by wengwenchao123** [comment]
AGCRN中其实并没有使用teacher_forcing，因为它并不是常规意义上的encoder-decoder架构的模型，他是在encoder后面加了一个线性层进行预测。他这边有这个内容可能是以为他的这个模型是以一个RNN为基础encoder-decoder模型修改过来的，当时修改了模型的其他部分，这部分因为没有引起bug就没做修改了

**Comment by OvOYu** [comment]
终于明白了！实在感谢您的热情帮助，祝好！！！

**Comment by wengwenchao123** [comment]
不客气，感谢你对本工作的关注，也欢迎你关注我最新发的RGDAN的论文，相关代码也已经放在github上了。

**Comment by OvOYu** [comment]
好的 祝贺你们出色的工作 祝好!

**Comment by OvOYu** [comment]
再打扰您一下，我有个问题：AGCRN中是归一化了data和lable吗 
![image](https://github.com/wengwenchao123/DDGCRN/assets/107761563/f9af3979-7b8c-453e-96fb-f5fc8814246d)
训练中是用归一化后的data，算loss的时候并没有反归一化output，直接与反归一化后的label对比，是这样的吗

**Comment by OvOYu** [comment]
![image](https://github.com/wengwenchao123/DDGCRN/assets/107761563/c2e25e0f-a389-42a0-9d1f-fdc88204d3f1)
处理数据时他应该是对整个数据集归一化再拆分为data和lable，算loss的时候他输出的output没有反归一化，跟反归一化的lable算loss，请问您我这个理解是否有错呢

**Comment by OvOYu** [comment]
![image](https://github.com/wengwenchao123/DDGCRN/assets/107761563/b92be4d6-a824-4572-8287-56422d48016a)
在您的代码中，处理数据时只归一化了output,在反归一化跟未未归一化的lable算loss，我认为这个是正确的，AGCRN的那个代码不知道我理解的有问题吗

**Comment by wengwenchao123** [comment]
> 再打扰您一下，我有个问题：AGCRN中是归一化了data和lable吗 ![image](https://private-user-images.githubusercontent.com/107761563/302181144-f9af3979-7b8c-453e-96fb-f5fc8814246d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTM3MzgsIm5iZiI6MTcwNzExMzQzOCwicGF0aCI6Ii8xMDc3NjE1NjMvMzAyMTgxMTQ0LWY5YWYzOTc5LTdiOGMtNDUzZS05NmZiLWY1ZmM4ODE0MjQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNjEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTk2ZTQwMmI2ZGM3ZjkyYTY0ZjFkYTBjNzFkOWFjYzBiMGQ3M2JjMDk1OGI2YjQ5ZTFkZTUwZjJmNzQwMGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2MbntLgpibLDRahu7VZLp-gcuhDKCxipY4bLGr0JwjM) 训练中是用归一化后的data，算loss的时候并没有反归一化output，直接与反归一化后的label对比，是这样的吗

**Comment by wengwenchao123** [comment]
> 再打扰您一下，我有个问题：AGCRN中是归一化了data和lable吗 ![image](https://private-user-images.githubusercontent.com/107761563/302181144-f9af3979-7b8c-453e-96fb-f5fc8814246d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTM3MzgsIm5iZiI6MTcwNzExMzQzOCwicGF0aCI6Ii8xMDc3NjE1NjMvMzAyMTgxMTQ0LWY5YWYzOTc5LTdiOGMtNDUzZS05NmZiLWY1ZmM4ODE0MjQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNjEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTk2ZTQwMmI2ZGM3ZjkyYTY0ZjFkYTBjNzFkOWFjYzBiMGQ3M2JjMDk1OGI2YjQ5ZTFkZTUwZjJmNzQwMGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2MbntLgpibLDRahu7VZLp-gcuhDKCxipY4bLGr0JwjM) 训练中是用归一化后的data，算loss的时候并没有反归一化output，直接与反归一化后的label对比，是这样的吗

抱歉，刚才出去吃了个饭，你的理解是正确的，AGCRN中是在数据处理那边直接归一化了data和label。

**Comment by wengwenchao123** [comment]
> ![image](https://private-user-images.githubusercontent.com/107761563/302181772-c2e25e0f-a389-42a0-9d1f-fdc88204d3f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTM3MzgsIm5iZiI6MTcwNzExMzQzOCwicGF0aCI6Ii8xMDc3NjE1NjMvMzAyMTgxNzcyLWMyZTI1ZTBmLWEzODktNDJhMC05ZDFmLWZkYzg4MjA0ZDNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNjEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDU1YmEyODQ4ZWJjMzBiYjkyYzBjNDRiM2I5MDU0ODE3YWI1N2U3NmM4YTBlZjIzY2NiZGViMDQ3ZWM0NjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pfRmqlXCUDIKUVjEh1LncoJQ35P6eCfMRgOlo2b8RUM) 处理数据时他应该是对整个数据集归一化再拆分为data和lable，算loss的时候他输出的output没有反归一化，跟反归一化的lable算loss，请问您我这个理解是否有错呢

有点区别，应该说是先记录了整个数据集的mean和std，然后拆分数据集

**Comment by wengwenchao123** [comment]
> ![image](https://private-user-images.githubusercontent.com/107761563/302184027-b92be4d6-a824-4572-8287-56422d48016a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTM3MzgsIm5iZiI6MTcwNzExMzQzOCwicGF0aCI6Ii8xMDc3NjE1NjMvMzAyMTg0MDI3LWI5MmJlNGQ2LWE4MjQtNDU3Mi04Mjg3LTU2NDIyZDQ4MDE2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNjEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmExNThkMzdiYmRkMDU3MjRhNDg1NDJiYjAzM2MyNDAxMzJkNDNmZTNlNWJmNDgxZWJjZGZmZmE5NTYwNjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-3ywcJ0ciNkrje-qyH0UudFU8DKP71LpQKint5JY61A) 在您的代码中，处理数据时只归一化了output,在反归一化跟未未归一化的lable算loss，我认为这个是正确的，AGCRN的那个代码不知道我理解的有问题吗

你的说法稍微有点问题，应该是在我的代码里面我只归一化了我的data，然后将根据data得到的output进行反归一化，然后跟没有归一化的label算loss。

其实一般来说大部分人的做法是将data和label同时归一化然后反归一化，我一开始也是这么做的，这种做法其实和我现在的做法在MAE和RMSE上没什么差别，因为他们对小误差值不敏感，但是在03数据集上会导致MAPE暴增，所以我才改成了现在的写法，其实要按同时同时归一化然后反归一化也行，这样子的话需要再mask_MAPE那边设置0.01还是0.001来屏蔽那边因为反归一化导致原本为0的label。

**Comment by OvOYu** [comment]
是的，您的代码的意思跟您说的一样，我理解的也是那样。AGCRN归一化了x和y，算loss的时候只反归一化了y，就这里我不是很明白，他最后没有反归一化output，但是保存的npy似乎是反归一化后的，难道AGCRN用归一化的数据输出反归一化后的数据

**Comment by wengwenchao123** [comment]
> 是的，您的代码的意思跟您说的一样，我理解的也是那样。AGCRN归一化了x和y，算loss的时候只反归一化了y，就这里我不是很明白，他最后没有反归一化output，但是保存的npy似乎是反归一化后的，难道AGCRN用归一化的数据输出反归一化后的数据

是这样子的，我们的目的是希望模型能够去拟合没有归一化过得label的数据对吧，那意味着不管我们使用的data是归一化过的还是没有归一化过的，只要我们是跟真实数据大小的label进行loss计算和训练，那模型输出的就是跟label大小的数值了。

我们对label进行归一化和反归一化，还是像我现在直接使用没有归一化的label，本质上都是为了拟合label的真实值，只是数据处理方式有些差别而已。
但是因为直接拟合label的真实值可能会出现label的真实值过大而很难训练的问题，所以才出现归一化的手段来帮助快速训练以及得到更好的效果。

**Comment by OvOYu** [comment]
豁然开朗了，真的感激您的帮助！

**Comment by wengwenchao123** [comment]
能帮到你就好

**Comment by OvOYu** [comment]
晚上好，非常感谢您的帮助。想请教下您关于学习率的问题。我观察到模型中默认没开启lr_decay = False，即学习率衰减默认关闭，3/4/8的lr_init = 0.003，7为lr_init = 0.00075，初始值是因为经过试验这样最优吗？lr_decay 您在训练时有开启吗，设置为True对性能是否有提升呢？

**Comment by wengwenchao123** [comment]
我是没有使用学习率衰减的，根据我测试来看其实没有什么太大的帮助，有可能会因为设置不合适变差一点点，至于你说的3/4/8的lr_init = 0.003，7为lr_init = 0.00075，这个是因为batchsize的原因，因为7的batchsize是16，其他的是64，我就按比例减少了学习率，一般减少batchsize的时候也要减少学习率以免出现学习率过大的问题。至于这个是不是最优的，我试过0.003和0.001，最终效果上基本没差别，0.003训练快很多，所以我就用0.003了

**Comment by OvOYu** [comment]
感谢大佬的解答！新年快乐！

**Comment by wengwenchao123** [comment]
也祝你新年快乐！

**Comment by OvOYu** [comment]
再打扰您一下，我对论文采用的分段学习在代码中如何体现不是很了解。现在的BasticTrainer是没有采用分段学习吗，根据之前的issue，似乎是在下图设置为20实现吗。
![image](https://github.com/wengwenchao123/DDGCRN/assets/107761563/1f40b7f7-99de-4fc0-bfe1-62389596e3e2)
按照分段学习是逐渐增加更多的层，是不是还要在model中修改呢？

**Comment by wengwenchao123** [comment]
是的，我是在这边设置成20来执行分段学习的，按照分段学习的思想是逐渐增加更多层，如果需要更多层的话模型内部的写法是要修改一下的，但是根据我做的实验来看，两层效果是最好的，那就没必要优化代码写成多层的形式，所以我就保持了一开始的写法提交上来了。另外如我论文中写的，分段学习并不会影响最终效果，如果资源足够的情况下，不用分段学习也是不错的选择。

**Comment by OvOYu** [comment]
突然明白了！感谢您的耐心指导！祝你越来越好，一切顺利！（题外话，好像看到您在考雅思，您打算国内985还是出国呢哈哈，我比您小一届应该，期待您的好消息与经验分享，follow你哈哈）

**Comment by wengwenchao123** [comment]
最后是国内双非，不过老师不错，如果有需要的话可以加我vx：wwcwwc_123 ，也期待以后能多交流和合作

**Comment by OvOYu** [comment]
加了哈哈 恭喜啊！！
