### ISSUE TITLE
Missing argument "days_per_week" in Args

### ISSUE THREAD

**Issue by hygeng** [wengwenchao123/DDGCRN#9]
I have fixed the issue myself, but I wanted to remind that "days_per_week" is missing in line 103 of the file "lib/dataloader.py".
You may need to add the following in the "run.py" file so that the code can be run swiftly.
`args.add_argument('--days_per_week', default=config['data']['days_per_week'], type=int)`

**Comment by wengwenchao123** [comment]
I'm sorry, that was my mistake. I have already modified the relevant code in run.py. Thank you for bringing it to my attention.
